Bump runtime to 23.08
flathub/org.quetoo.Quetoo pull request #9
Opened 2023-09-07 14:04 UTC by bbhtt

Closes https://github.com/flathub/org.quetoo.Quetoo/issues/7

2023-09-07 15:28 UTC, bbhtt commented
Runs

2024-05-27 23:28 UTC, AsciiWolf commented
@jdolan Any chance this could get merged?

2024-05-27 23:28 UTC, AsciiWolf commented
bot, build

2024-05-27 23:46 UTC, AsciiWolf commented
Needs AppStream metadata update.

2024-05-28 02:33 UTC, bbhtt commented
> @jdolan Any chance this could get merged?

If you can test I'll merge. I doubt the maintainer is active anymore here.

2024-05-28 15:43 UTC, AsciiWolf commented
Replaced by #10.

2024-05-28 16:20 UTC, AsciiWolf requested changes
Duplicated screenshot fix.

2024-05-28 16:20 UTC, AsciiWolf commented on org.quetoo.Quetoo.appdata.xml
> +      <image>https://farm3.staticflickr.com/2818/33459192014_2e76a22a09_c.jpg</image>
```suggestion
      <image>https://farm8.staticflickr.com/7191/6840396554_70726caf45_c.jpg</image>
```

2024-05-29 01:50 UTC, merged